# Generated by Django 4.1.7 on 2023-05-11 19:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatePollRespondents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='answer',
            name='multiple_options',
            field=models.ManyToManyField(blank=True, related_name='multiple_options', to='polls.option'),
        ),
        migrations.AddField(
            model_name='answer',
            name='single_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='single_option', to='polls.option'),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 22, 36, 11, 825055)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 22, 36, 11, 825055)),
        ),
        migrations.DeleteModel(
            name='PrivatePoll',
        ),
        migrations.AddField(
            model_name='privatepollrespondents',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='polls.poll'),
        ),
        migrations.AddField(
            model_name='privatepollrespondents',
            name='pollees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
