# Generated by Django 4.1.7 on 2023-05-17 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_answer_multiple_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 23, 5, 1, 678434)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 23, 5, 1, 678434)),
        ),
    ]
