# Generated by Django 4.1.7 on 2023-05-17 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_poll_creation_date_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='multiple_options',
            field=models.ManyToManyField(blank=True, related_name='multiple_options', to='polls.option'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 23, 8, 7, 859805)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 23, 8, 7, 859805)),
        ),
    ]
